server:
  port: 8080
  servlet:
    context-path: /api

feishu:
  app-id: ${FEISHU_APP_ID:default_app_id}
  app-secret: ${FEISHU_APP_SECRET:default_secret}
  verification-token: ${FEISHU_VERIFICATION_TOKEN:default_token}
  base:
    app-id: ${FEISHU_BASE_APP_ID:base_app_id}
    table-id: ${FEISHU_BASE_TABLE_ID:table_id}

ai:
  service-url: ${AI_SERVICE_URL:https://ai-service.example.com/process}
  callback-url: ${AI_CALLBACK_URL:https://your-domain.com/api/callback/ai}
  timeout: 10000 # 10 seconds

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  lock:
    expire-time: 30
    wait-time: 5
    retry-interval: 100

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        failure-rate-threshold: 50
        slow-call-rate-threshold: 30
        slow-call-duration-threshold: 5s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: TIME_BASED
        sliding-window-size: 60
        minimum-number-of-calls: 10
        wait-duration-in-open-state: 30s
    instances:
      aiService:
        base-config: default

spring:
  task:
    execution:
      pool:
        core-size: 10
        max-size: 50
        queue-capacity: 1000
  redis:
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5